<?php

namespace ApiBundle\Repository;

/**
 * FreeChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreeChampionRepository extends \Doctrine\ORM\EntityRepository
{
}
