<?php

namespace RiotBundle\Repository;

/**
 * UserChampsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserChampsRepository extends \Doctrine\ORM\EntityRepository
{
}
